config/routes.rb
Casehappy::Application.routes.draw do

  resources :stores

  resources :charges
  
  resources :carts

  devise_for :users
  resources :orders

  root to: "stores#new"

  get '/choose' => 'pages#choose'

  post '/carts/charge/:id' => 'carts#thankyou'
  get '/carts/charge/:id' => 'carts#thankyou'

  get '/stores/preview/:id' => 'stores#preview'

  

end

app/models/store.rb
class Store < ActiveRecord::Base
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy, :preview]

  def preview
    
    @session_id = request.session_options[:id]
    @cart = Cart.find_by session: @session_id
    @orders = Order.where(cart: @cart.id)
    render layout: 'display'
  end

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @session_id = request.session_options[:id]
    @cart = Cart.find_by session: @session_id
    @orders = Order.where(cart: @cart.id)

  end

  # GET /stores/new
  def new
    @store = Store.new
    
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store }
      else
        format.html { render action: 'new' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :title, :logo, :session)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :logo %><br>
    <%= f.text_area :logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h1>Listing stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Logo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.title %></td>
        <td><%= store.logo %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
	<div id="store-profile-form">
		<br>
		<div class="container">
			<center>
				<h1>Create your <span class="instacase-brand">MerchJoy</span> store</h1>
			</center>
			<br>
			<div class="well">
				<div class="row">
					<div class="col-md-8 col-md-offset-2">

							<%= form_for(@store) do |f| %>
							  <% if @store.errors.any? %>
							    <div id="error_explanation">
							      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

							      <ul>
							      <% @store.errors.full_messages.each do |msg| %>
							        <li><%= msg %></li>
							      <% end %>
							      </ul>
							    </div>
							  <% end %>

						  <div class="form-group">
						    <label for="storeNameInput">Store Name</label>
						    <div class="row">
							    <div class="col-xs-6">
							    	<%= f.text_field :name, :class=>"form-control", :id=>"storeNameInput", :placeholder=>"storename" %>
								  </div>
								  <div class="col-xs-6">
								  	<span style="background-color:transparent; border: none; box-shadow:none; padding-left:0; margin-left:-15px;" class="form-control">
									  	.merchjoy.com
									  </span>
								  </div>
								 </div>
						  </div>
						  <div class="form-group">
						    <label for="storeTitleInput">Store Title</label>
						    <div class="row">
							    <div class="col-xs-6">
							    	<%= f.text_field :title, :class=>"form-control", :id=>"storeTitleInput", :placeholder=>"My MerchJoy Store" %>
						    	</div>
						    </div>
						  </div>
						  <div class="form-group">
						    <label for="storeLogo">Store Logo Image</label>
						    <div class="row">
						    	<div class="col-xs-6">
								    <input type="file" id="storeLogo">

								    <p class="help-block">200px by 200px image that goes into your store header</p>

								    <%= f.text_area :logo, :class=>"hidden", :id=>"store-logo" %>
								    <%= f.text_area :session, :class=>"hidden", :id=>"store-session", :value=> request.session_options[:id] %>
								  </div>
								  <div class="col-xs-6">
								  	<img id="uploaded-img" />
								  </div>
						  </div>
						  <div class="form-group">
						    <label for="storeThene">Choose Store Theme</label>
						    <div class="row">
						    	<div class="col-xs-6">
								    <select id="font-selector" class="form-control">
											<option>MerchJoy Default</option>
											<option>Daylight</option>
											<option>Nightfall</option>
											<option>Blue Sky</option>
											<option>Landscape</option>
											<option>War Zone</option>							
											<option>Villager</option>
											<option>Custom</option>
										</select>
								  </div>
						  </div>
						  <div class="checkbox">
						    <label>
						      <input type="checkbox"> Import products from existing stores
						    </label>
						  </div>
						  	<button class="btn btn-info pull-right" >Create Store
						  	</button>
						  	<%= f.submit "Create New Store", :id=>"submitStore", :class=>"btn btn-primary btn-lg hidden"  %>
						<% end %>
					</div>			
				</div>
			</div>
		</div>
	</div>

app/views/stores/preview.html.erb
	<div id="store-profile-form-mobile" style="position:relative">
				<div class="continer-fluid" style="position:fixed; width: 100%; z-index:100000;">
					<div id="store-header-mobile" style="border: 1px solid #000;">
						<div class="row">
							<div class="col-xs-12">
								<img id="store-logo-mobile" src="<%= @store.logo %>" />

								<span id="store-title-mobile"><span id="storeTitle"><%= @store.title %></span></span>
								<span id="store-sub-mobile">The Official Store</span>
								<div style="color:#eee; position:absolute; top:10px; right: 24px; font-size: 18px;">
									<span id="store-shopping-cart" class="glyphicon glyphicon-shopping-cart" style="margin-right: 10px;"></span>
									<span id="store-home" class="glyphicon glyphicon-home"></span>
								</div>

							</div>
						</div>
					</div>
				</div>
					<div id="choose-product-menu-mobile" style="padding-top: 80px;">
					
				          <% @orders.reverse.each do |order| %>
				            		<div class="product-display" style="height:300px; width: 100%; overflow: hidden; background-color: #fff; position:relative;"><iframe style="height:2000px; width:2000px; zoom: 0.6; -webkit-transform:scale(0.6); margin-top:-400px; margin-left: -440px; border: transparent;" src="/orders/<%= order.id %>"></iframe>
				            		<a href="/orders/<%= order.id %>" style="position:absolute; top:0; left:0; width:220px; height: 380px;" onclick="return popitup('/orders/<%= order.id %>')"></a>
				            		<div style="position:absolute; top:0px; height:300px; width:180px; background-color:#fff; right: 0px; padding:10px;" >
				            			<h4 style="color:#2c3e50"><%= order.name %></h4>
				            			<h5 style="color:#34495e;; font-weight:300; font-style:italic;">L-O-V-E. For Clash fans that want to show their love right on the back of their phones.</h5>
				            			<h6 class="darkgray"><%= order.model %> Phone Case
				            				<ul style="font-size: 12px; font-weight: 200; padding-left: 20px; margin-top:4px;">
				            					<li>3.96 x 6.17 in (w x h)
				            					</li>
				            					<li>Shatter-proof polycarbonate 
				            					</li>
				            					<li>Wrap-Around Printing™
				            					</li>
				            				</ul>
				            			</h6>
				            			<div class="price-tag">$20</div>

				            		</div>
				            	</div>

				            		<div class="btn btn-lg btn-block btn-stripe" style="font-size: 20px;">Add to Cart</div>
				            <!--tr>
				            	<td style="position:relative" ><%= link_to edit_order_path(order) do %>
				            		<div style="height:164px; width: 120px; overflow: hidden;"><iframe style="height:1400px; width:900px; zoom: 0.35; -webkit-transform:scale(0.35); margin-top:-470px; margin-left: -300px;" src="/orders/<%= order.id %>"></iframe></div>
				            		<% end %><a href="/orders/<%= order.id %>" style="position:absolute; top:0; left:0; width:130px; height: 180px;" onclick="return popitup('/orders/<%= order.id %>')"></a></td>
				            	<td><%= order.model %></td>
				            	<td><%= order.name %></td>
				            	<td><%= number_to_currency(order.quantity * order.price, options = {format: "%u%n", precision: 0})  %></td>
				            	<td><a>https://<span id="storeName"><%= @store.name %></span>.merchjoy.com/<%= order.name.gsub(/ /,'-').downcase %></a></td>
				            	<td>
				            		<%= link_to edit_order_path(order) do %>
				            			<span class="glyphicon glyphicon-pencil" style="margin-right: 10px;"></span>
				            		<% end %>
				            		<%= link_to order, method: :delete, data: { confirm: 'Are you sure?' }, :class => "flatred" do %>
				            			<span class="glyphicon glyphicon-remove"></span>
				            		<% end %>
				            	</td>
				            </tr-->
				            <br>
				            <br>
				          <% end %>

					</div>
				</div>
	</div>

app/views/stores/show.html.erb
	<div id="store-profile-form">
		<script language="javascript" type="text/javascript">
		<!--
		function popitup(url) {
			newwindow=window.open(url,'name','height=500,width=380');
			if (window.focus) {newwindow.focus()}
			return false;
		}

		// -->
		</script>
		<br>
		<div class="container">
			<div class="well">
				<div class="continer-fluid">
					<div id="store-header">
						<div class="row">
							<div class="col-xs-12">
								<img id="store-logo" src="<%= @store.logo %>" />

								<span id="store-title"><span id="storeTitle"><%= @store.title %></span><span style="margin:5px; padding: 5px; font-size: 20px; " class="glyphicon glyphicon-pencil"></span></span>
								<span id="store-sub">The Official Store</span>
								<span id="store-url">https://<span id="storeName"><%= @store.name %></span>.merchjoy.com <span style="margin:2px; color:#ddd; border-radius: 1px; padding: 2px; font-size: 12px;" class="glyphicon glyphicon-pencil"></span></span>

							</div>
						</div>
					</div>
					<div id="choose-product-menu">
						<div id="add-new-merch" style="background-color: #fafbfc; border: 2px dashed #eee;">
							<h3 style="font-weight: 300; padding-left: 10px;">Add new merchandise</h3>
							<div class="product small">
								<a href="/choose">
									<button><img src="/images/product-tshirt.png" /><span class="tag">T-shirt</span></button>
								</a>
							</div><div class="product small">
								<a href="/choose">
									<button><img src="/images/product-case.png" /><span class="tag">Phone Case</span></button>
								</a>
							</div><div class="product small">
								<a href="/choose">
									<button><img src="/images/product-poster.png" /><span class="tag">Poster</span></button>
								</a>
							</div><div class="product small">
								<a href="/choose">
									<button><img src="/images/product-mug.png" /><span class="tag">Mugs</span></button>
								</a>
							</div><div class="product small">
								<a href="/choose">
									<button><img src="/images/product-misc.png" style="visibility;"/><span class="tag">Others</span></button>
								</a>
							</div>

						</div>
						<div class="finished-product">

							<table class="table">
				        <thead>
				          <tr>
				            <th width="120px"></th>
				            <th>Product SKU</th>
								  	<th>Template Name</th>
								  	<th>Base Price</th>
								  	<th>URL</th>
				            <th width="80px"></th>
				          </tr>
				        </thead>

				        <tbody>
				          <% @orders.each do |order| %>
				            <tr>
				            	<td style="position:relative" ><%= link_to edit_order_path(order) do %>
				            		<div style="height:164px; width: 120px; overflow: hidden;"><iframe style="height:1400px; width:900px; zoom: 0.35; -webkit-transform:scale(0.35); margin-top:-470px; margin-left: -300px;" src="/orders/<%= order.id %>"></iframe></div>
				            		<% end %><a href="/orders/<%= order.id %>" style="position:absolute; top:0; left:0; width:130px; height: 180px;" onclick="return popitup('/orders/<%= order.id %>')"></a></td>
				            	<td><%= order.model %></td>
				            	<td><%= order.name %></td>
				            	<td><%= number_to_currency(order.quantity * order.price, options = {format: "%u%n", precision: 0})  %></td>
				            	<td><a>https://<span id="storeName"><%= @store.name %></span>.merchjoy.com/<%= order.name.gsub(/ /,'-').downcase %></a></td>
				            	<td>
				            		<%= link_to edit_order_path(order) do %>
				            			<span class="glyphicon glyphicon-pencil" style="margin-right: 10px;"></span>
				            		<% end %>
				            		<%= link_to order, method: :delete, data: { confirm: 'Are you sure?' }, :class => "flatred" do %>
				            			<span class="glyphicon glyphicon-remove"></span>
				            		<% end %>
				            	</td>
				            </tr>
				          <% end %>
				        </tbody>
				      </table>
						</div>
					</div>
				</div>

			</div>
		</div>
		<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
	</div>