config/routes.rb
Casehappy::Application.routes.draw do

  resources :stores

  resources :charges
  
  resources :carts

  devise_for :users
  resources :orders

  root to: "stores#new"

  get '/choose' => 'pages#choose'

  post '/carts/charge/:id' => 'carts#thankyou'
  get '/carts/charge/:id' => 'carts#thankyou'

  get '/stores/preview/:id' => 'stores#preview'

  

end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  #def index
  #  @orders = Order.all
  #end

  # GET /orders/1
  # GET /orders/1.json
  def show

    @variable = params[:user]

    @order = Order.find(params[:id])

    if @variable.nil?
      puts 'Nil'
      @canvas = @order.canvas
    else
      puts @variable

      @canvas = @order.canvas.gsub(/{{user}}/, @variable)
    end

    @cart = Cart.find(@order.cart.to_s)
    @session_id = request.session_options[:id]
    if @session_id == @cart.session
      render layout: 'display'
    else
      redirect_to(root_url)
    end


    
  end

  # GET /orders/new
  def new
    @model = params[:model]
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
    @cart = Cart.find(@order.cart.to_s)
    @session_id = request.session_options[:id]
    if @session_id == @cart.session

    else
      redirect_to(root_url)
    end
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save

        if params[:commit] == "save"
          format.html { redirect_to edit_order_path(@order) }
          format.json { render action: 'edit', status: :created, location: @order }
        else
          format.html { redirect_to @store }
          format.json { render action: 'show', status: :created, location: @cart }
        end
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update

    respond_to do |format|
      if @order.update(order_params)

        if params[:commit] == "save"
          format.html { redirect_to edit_order_path(@order) }
          format.json { head :no_content }
        else
          format.html { redirect_to @store }
          format.json { head :no_content }
        end
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to @store }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user, :quantity, :canvas, :model, :offset, :startW, :image, :cart, :price, :name, :description)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :canvas %><br>
    <%= f.text_field :canvas %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
		<div class="container-fluid thin-padding" id="all-select">
		<div id="canvas-container">
			<canvas id="insta-canvas"></canvas>
			<div class="hidden" id="outside-edge">
			</div>
			<div class="" id="outside-border">
			</div>
			<div class="" id="inside-border">
			</div>
			<div class="" id="camera-border">
			</div>


			<div id="control-box">
				<button class="control-icon" id="upload-icon">
					<span class="glyphicon glyphicon-upload"></span>
					<div class="hidden-on-mobile control-label">Upload Image</div>
				</button>
				<button class="control-icon" id="text-icon">
					<span class="glyphicon glyphicon-font"></span>
					<div class="hidden-on-mobile control-label">Add Text</div>
				</button>
				<button class="control-icon" id="clipart-icon">
					<span class="glyphicon glyphicon-heart-empty"></span>
					<div class="hidden-on-mobile control-label">Add Clipart</div>
				</button>
				<button class="control-icon" id="background-icon">
					<span class="glyphicon glyphicon-adjust"></span>
					<div class="hidden-on-mobile control-label">Background Color</div>
				</button>
				<button class="control-icon" id="cart-icon">
					<span class="glyphicon glyphicon-floppy-disk"></span>
					<div class="hidden-on-mobile control-label" id="order-save">Save + Preview</div>
				</button>
			</div>

			<div class="hidden" id="options-box">
				<button class="object-icon" id="text-remove-icon">
					<span class="glyphicon glyphicon-remove"></span>
				</button>
				<button class="hidden object-icon" id="move-up-icon">
					<span class="glyphicon glyphicon-arrow-up"></span>
				</button>
				<button class="hidden object-icon" id="move-down-icon">
					<span class="glyphicon glyphicon-arrow-down"></span>
				</button>
			</div>
			<div class="hidden" id="object-box">
				<button class="resize-icon" id="resize-TL-icon">
					<span class="glyphicon glyphicon-resize-full"></span>
				</button>
				<button class="resize-icon" id="resize-TR-icon">
					<span class="glyphicon glyphicon-resize-full"></span>
				</button>
				<button class="resize-icon" id="resize-BL-icon">
					<span class="glyphicon glyphicon-resize-full"></span>
				</button>
				<button class="resize-icon" id="resize-BR-icon">
					<span class="glyphicon glyphicon-resize-full"></span>
				</button>
				<button class="resize-icon" id="rotate-icon">
					<span class="glyphicon glyphicon-repeat"></span>
				</button>
			</div>

			<div class="command-box hidden-on-mobile" id="order-box">
				<!--form role="form"-->
					<div class="row">
						<div class="col-xs-12"><h2>Current Order</h2></div>
					</div>
					<div class="row form-area" id="order-area">
						<div class="col-xs-4 hidden-on-mobile">
					  	<label for="order-quantity" class="hidden-on-mobile">Quantity</label>
					  	<label for="order-quantity" class="hidden-on-web">#</label>
					  </div>
					  <div class="col-sm-8">
					   	<input type="text" class="form-control" id="order-quantity" placeholder="1" value="1">
					  </div>
				    <div class="col-xs-4 hidden-on-mobile">
					    <label for="order-color">Model</label>
					  </div>
					  <div class="col-sm-8">
					    <label for="order-color"><%= @order.model %></label>
					  </div>
					  <div class="col-xs-8 col-sm-offset-4">
						  <div class="checkbox">
						    <input type="checkbox" id="order-edges"><span class="order-label">Don't print on sides</span>
						  </div>
						</div>
					  <div class="col-xs-4 hidden-on-mobile">
					    <label for="order-color">Total</label>
					  </div>
					  <div class="col-sm-8" id="order-total">
					    $<span id="order-value">20</span>
					  </div>
					</div>
					<div class="col-xs-12">
					   <button class="btn btn-primary btn-block btn-lg" id="order-checkout"><span class="glyphicon glyphicon-shopping-cart"></span> Add to Cart</button>
					</div>
				<!--/form-->
			</div>

			<div class="hidden command-box" id="clipart-box">
				<button class="close-button">
					<span class="glyphicon glyphicon-remove"></span>
				</button>
				<div class="row">
					<div class="col-xs-12"><h2>Select clipart</h2></div>
				</div>
				<div class="row form-area">
					<img src="/clipart/icon_1108.png">
					<img src="/clipart/icon_1642.png">
					<img src="/clipart/icon_3708.png">
					<img src="/clipart/icon_4895.png">
					<img src="/clipart/icon_8124.png">
					<img src="/clipart/icon_19462.png">
					<img src="/clipart/icon_30130.png">
					<img src="/clipart/icon_35195.png">
					<img src="/clipart/icon_35490.png">
				</div>
			</div>

			<div class="command-box hidden" id="background-box">
				<button class="close-button">
					<span class="glyphicon glyphicon-remove"></span>
				</button>
				<div class="row">
					<div class="col-xs-12">
						<h2>Background color</h2>
					</div>
					<div class="col-xs-12">
						<input id='bkg-colorpicker' />
					</div>
				</div>
			</div>

			<div class="hidden command-box hidden-on-mobile" id="image-box">
				<button class="close-button">
					<span class="glyphicon glyphicon-remove"></span>
				</button>
				<div class="row">
					<div class="col-xs-12"><h2>Adjust image</h2></div>
				</div>
				<div class="row form-area">
					<div class="col-xs-12">
						<div class="panel panel-info" id="filter-box">
							<div class="panel-heading">
						    <h3 class="panel-title">Filters</h3>
						  </div>
						  <div class="panel-body">
						  	<div class="row">
						  		<div class="col-xs-4">
								    <button id="filter-Grayscale">Gray<span style="color:#555;">scale</span></button>
								  </div>
								  <div class="col-xs-4">
										<button id="filter-Sepia2">Sepia</button>
									</div>
									<div class="col-xs-4">
										<button id="filter-Sepia">Cool</button>
									</div>
								</div>
								<div class="row hidden">
									<div class="col-xs-4">
								    <button id="filter-Blur">Blur</button>
								  </div>
								  <div class="col-xs-4">
										<button id="filter-Sharpen">Sharpen</button>
									</div>
									<div class="col-xs-4">
										<button id="filter-Emboss">Emboss</button>
									</div>
								</div>
						  </div>
						</div>
					</div>
					<div class="col-xs-12">
						<div class="row">
							<div class="col-xs-12">
								<input type="checkbox" id="filter-tint-color">
								<span class="white-label">Adjust image color </span> 
								<input type="color" class="pull-right" id="filter-tint-color-intensity">
							</div>
						</div>
						<div class="row">
							<div class="col-xs-4">
								Intensity:
							</div>
							<div class="col-xs-8">
								<input type="range" name="points" min="0" max="1" value="0.4" step="0.1" id="filter-tint-color-opacity">
							</div>
						</div>
					</div>
					<div class="col-xs-12">
						<div class="row">
							<div class="col-xs-12">
								<input type="checkbox" id="filter-brighten">
								<span class="white-label">Brighten </span> 
							</div>
						</div>
						<div class="row">
							<div class="col-xs-4">
								Intensity:
							</div>
							<div class="col-xs-8">
								<input type="range" name="points" min="0" max="255" value="100" id="filter-brighten-intensity">
							</div>
						</div>
					</div>
					<div class="col-xs-12">
						<div class="row">
							<div class="col-xs-12">
								<input type="checkbox" id="filter-pixelate">
								<span class="white-label">Pixelate </span> 
							</div>
						</div>
						<div class="row">
							<div class="col-xs-4">
								Strength:
							</div>
							<div class="col-xs-8">
								<input type="range" name="points" min="2" max="20" value="4" id="filter-pixelate-intensity">
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="hidden command-box hidden-on-mobile" id="font-box">
				<button class="close-button">
					<span class="glyphicon glyphicon-remove"></span>
				</button>
				<div class="row">
					<div class="col-xs-12"><h2>Edit text</h2></div>
				</div>
				<div class="row form-area">
					<div class="col-xs-12">
						<div class="row">

							<div class="col-xs-12">
								<textarea rows="3" class="form-control" id="font-textarea" placeholder="Your Text"></textarea>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-6">

								<!--TODO - put in custom selector showing font family before selection-->
								<select id="font-selector" class="form-control">
									<option>Select a font</option>
									<option>Abril Fatface</option>
									<option>Arvo</option>
									<option>Cardo</option>
									<option>Courier New</option>
									<option>Droid Sans</option>							
									<option>Helvetica</option>
									<option>Josefin Slab</option>
									<option>Lato</option>
									<option>Lobster</option>
									<option>Montserrat Alternates</option>
									<option>Open Sans</option>
									<option>Oswald</option>
									<option>PT Mono</option>
									<option>Times New Roman</option>
									<option>Ubuntu</option>
									<option>Varela</option>
									<option>Vollkorn</option>
									<option>Wingdings</option>
								</select>
							</div>
						

							<div class="col-xs-6" id="font-align"> 
								<div class="btn-group pull-right">
								  <button type="button" class="btn btn-default" id="align-left"><span class="glyphicon glyphicon-align-left"></span></button>
								  <button type="button" class="btn btn-default" id="align-center"><span class="glyphicon glyphicon-align-center"></span></button>
								  <button type="button" class="btn btn-default" id="align-right"><span class="glyphicon glyphicon-align-right"></span></button>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12">
								<input id='colorpicker' />
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<input type='file' name="files[]" class="hidden" id="image-input" multiple/>
<div class="">
	<%= form_for(@order) do |f| %>

	  <div class="field">
	    <%= f.label :quantity %><br>
	    <%= f.number_field :quantity %>
	  </div>
	  <div class="field">
	    <%= f.label :canvas %><br>
	    <%= f.text_field :canvas %>
	  </div>
	  <div class="field">
	    <%= f.label :image %><br>
	    <%= f.text_field :image %>
	  </div>
	  <div class="field">
	    <%= f.label :offset %><br>
	    <%= f.text_field :offset %>
	  </div>
	  <div class="field">
	    <%= f.label :startW %><br>
	    <%= f.text_field :startW %>
	  </div>
	  <div class="field">
	    <%= f.label :price %><br>
	    <%= f.text_field :price %>
	  </div>
	  <div class="actions">
	    <%= f.submit "new", :id=>"submit-new" %>
	    <%= f.submit "save", :id=>"submit-save" %>
	  </div>
	  <br><br><br><br>
	<% end %>
</div>
		<div id="footer-font">
			<span style="font-family:'Abril Fatface'">iPhone</span><br>
			<span style="font-family:'Josefin Slab'">iPhone 5</span><br>
			<span style="font-family:'Arvo'">iPhone 4</span><br>
			<span style="font-family:'Cardo'">iPhone 5s</span><br>
			<span style="font-family:'Abril Fatface'">iPhone 4s</span><br>
			<span style="font-family:'Josefin Slab'">iPhone case</span><br>
			<span style="font-family:'Droid Sans'">Phone case</span><br>
			<span style="font-family:'Josefin Slab'">Custom case</span><br>
			<span style="font-family:'Lato'">Custom iPhone case</span><br>
			<span style="font-family:'Lobster'">Customized phone case</span><br>
			<span style="font-family:'Montserrat Alternates'">Customized iPhone case</span><br>
			<span style="font-family:'Open Sans'">Customized iPhone 5 case</span><br>
			<span style="font-family:'Oswald'">Create iPhone case</span><br>
			<span style="font-family:'PT Mono'">Create iPhone 5 case</span><br>
			<span style="font-family:'Ubuntu'">Customize iPhone case</span><br>
			<span style="font-family:'Varela'">Customize iPhone 5 case</span><br>
			<span style="font-family:'Vollkorn'">Make your own iPhone case</span><br>
		</div>
	</div>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Quantity</th>
      <th>Canvas</th>
      <th>Model</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user %></td>
        <td><%= order.quantity %></td>
        <td><%= order.canvas %></td>
        <td><%= order.model %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/show.html.erb
<div id="tridiv">
  <div class="scene" style="-webkit-transform:rotateX(-1464deg) rotateY(-43deg); -moz-transform:rotateX(-1464deg) rotateY(-43deg); -ms-transform:rotateX(-1464deg) rotateY(-43deg); transform:rotateX(-1464deg) rotateY(-43deg); ">
    <div class="shape cuboid-1 cub-1">
      <div class="face ft">
        <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.494118);"></div>
      </div>
      <div class="face bk">
        <div class="photon-shader-alt-side" style="background-image: url(<%= @order.image %>);"></div>
      </div>
      <div class="face rt">
        <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.54902);"></div>
      </div>
      <div class="face lt" style="-webkit-backface-visibility: hidden; border: 1px solid rgba(0, 0, 0, 0);">
        <div class="photon-shader-alt-top" style="background-image: url(<%= @order.image %>);"></div>
      </div>
      <div class="face lt" style="-webkit-backface-visibility: hidden; -webkit-transform: rotateY(90deg) translateX(-50%) translateY(-10%); z-index: 1000; height: 32px; ">
        <img class="photon-shader-alt-top-case" src='/images/case-top.png'></img>
      </div>
      <div class="face bm">
        <div class="photon-shader-alt" style="background-image: url('<%= @order.image %>');" id="main-face"></div>
      </div>
      <div class="face tp">
        <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.509804);"></div>
      </div>
      <div class="cr cr-0">
        <div class="face side s0">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.447059);"></div>
        </div>
        <div class="face side s1">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.345098);"></div>
        </div>
        <div class="face side s2">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.231373);"></div>
        </div>
      </div>
      <div class="cr cr-1">
        <div class="face side s0">
          <div class="photon-shader-alt-cr cr-1" style="background-image: url(<%= @order.image %>);"></div>
        </div>
        <div class="face side s1">
          <div class="photon-shader-alt-cr cr-2" style="background-image: url(<%= @order.image %>);"></div>
        </div>
        <div class="face side s2">
          <div class="photon-shader-alt-cr cr-3" style="background-image: url(<%= @order.image %>);"></div>
        </div>
      </div>
      <div class="cr cr-2">
        <div class="face side s0">
          <div class="photon-shader-alt-cr cr-4 " style="background-image: url(<%= @order.image %>);"></div>
        </div>
        <div class="face side s1">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.254902);"></div>
        </div>
        <div class="face side s2">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.364706);"></div>
        </div>
      </div>
      <div class="cr cr-3">
        <div class="face side s0">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.466667);"></div>
        </div>
        <div class="face side s1">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.533333);"></div>
        </div>
        <div class="face side s2">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.52549);"></div>
        </div>
      </div>
    </div>
    <div class="shape cuboid-2 cub-2">
      <div class="face ft">
        <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.494118);"></div>
      </div>
      <div class="face bk">
        <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.105882);"></div>
      </div>
      <div class="face bm">
        <div class="photon-shader" style="background-color: rgba(0, 100, 0, 0.509804);"></div>
      </div>
      <div class="face tp">
        <div class="photon-shader camera-lens" style="background-color: rgba(0, 0, 0, 0.0901961); left: -10px;"></div>
      </div>
      <div class="cr cr-0">
        <div class="face side s0">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.52549);"></div>
        </div>
        <div class="face side s1">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.533333);"></div>
        </div>
        <div class="face side s2">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.466667);"></div>
        </div>
      </div>
      <div class="cr cr-1">
        <div class="face side s0">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.364706);"></div>
        </div>
        <div class="face side s1">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.254902);"></div>
        </div>
        <div class="face side s2">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.14902);"></div>
        </div>
      </div>
      <div class="cr cr-2">
        <div class="face side s0">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.0745098);"></div>
        </div>
        <div class="face side s1">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.0627451);"></div>
        </div>
        <div class="face side s2">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.129412);"></div>
        </div>
      </div>
      <div class="cr cr-3">
        <div class="face side s0">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.231373);"></div>
        </div>
        <div class="face side s1">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.345098);"></div>
        </div>
        <div class="face side s2">
          <div class="photon-shader" style="background-color: rgba(0, 0, 0, 0.447059);"></div>
        </div>
      </div>
    </div>
  </div>
</div>

    <div class="container-fluid thin-padding hidden" id="all-select">
    <div id="canvas-container">
      <canvas id="insta-canvas"></canvas>
 
    </div>

    <input type='file' name="files[]" class="hidden" id="image-input" multiple/>
      <div class="">
        <%= form_for(@order) do |f| %>

          <div class="field">
            <%= f.label :quantity %><br>
            <%= f.number_field :quantity %>
          </div>
          <div class="field">
            <%= f.label :canvas %><br>
            <%= f.text_field :canvas, :value=> @canvas %>
          </div>
          <div class="field">
            <%= f.label :image %><br>
            <%= f.text_field :image %>
          </div>
          <div class="field">
            <%= f.label :offset %><br>
            <%= f.text_field :offset %>
          </div>
          <div class="field">
            <%= f.label :startW %><br>
            <%= f.text_field :startW %>
          </div>
          <div class="field">
            <%= f.label :price %><br>
            <%= f.text_field :price %>
          </div>
          <div class="actions">
            <%= f.submit "new", :id=>"submit-new" %>
            <%= f.submit "save", :id=>"submit-save" %>
          </div>
          <br><br><br><br>
        <% end %>
      </div>
    <div id="footer-font">
      <span style="font-family:'Abril Fatface'">iPhone</span><br>
      <span style="font-family:'Josefin Slab'">iPhone 5</span><br>
      <span style="font-family:'Arvo'">iPhone 4</span><br>
      <span style="font-family:'Cardo'">iPhone 5s</span><br>
      <span style="font-family:'Abril Fatface'">iPhone 4s</span><br>
      <span style="font-family:'Josefin Slab'">iPhone case</span><br>
      <span style="font-family:'Droid Sans'">Phone case</span><br>
      <span style="font-family:'Josefin Slab'">Custom case</span><br>
      <span style="font-family:'Lato'">Custom iPhone case</span><br>
      <span style="font-family:'Lobster'">Customized phone case</span><br>
      <span style="font-family:'Montserrat Alternates'">Customized iPhone case</span><br>
      <span style="font-family:'Open Sans'">Customized iPhone 5 case</span><br>
      <span style="font-family:'Oswald'">Create iPhone case</span><br>
      <span style="font-family:'PT Mono'">Create iPhone 5 case</span><br>
      <span style="font-family:'Ubuntu'">Customize iPhone case</span><br>
      <span style="font-family:'Varela'">Customize iPhone 5 case</span><br>
      <span style="font-family:'Vollkorn'">Make your own iPhone case</span><br>
    </div>
  </div>