config/routes.rb
Casehappy::Application.routes.draw do

  resources :stores

  resources :charges
  
  resources :carts

  devise_for :users
  resources :orders

  root to: "stores#new"

  get '/choose' => 'pages#choose'

  post '/carts/charge/:id' => 'carts#thankyou'
  get '/carts/charge/:id' => 'carts#thankyou'

  get '/stores/preview/:id' => 'stores#preview'

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show,:edit, :update, :destroy, :thankyou]
  
  # GET /carts
  # GET /carts.json
  #def index
  #  @carts = Cart.all
  #end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])
    @session_id = request.session_options[:id]
    redirect_to(root_url) unless @session_id == @cart.session
    @orders = Order.where(cart: params[:id])
    @cart_total = @orders.sum("quantity * price")
    @cart_items = @orders.sum("quantity")
  end

  def thankyou
    puts "Thank You Again"
    
    @cart = Cart.find(params[:id])
    puts @cart.id
    
    @cart.update_attribute(:session, "PAID")

  end

  # GET /carts/new
  #def new
  #  @cart = Cart.new
  #end

  # GET /carts/1/edit
  #def edit
  #  @cart = Cart.find(params[:id])
  #  @session_id = request.session_options[:id]
  #  redirect_to(root_url) unless @session_id == @cart.session
  #end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:user, :session, :total)
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :session %><br>
    <%= f.text_field :session %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Session</th>
      <th>Total</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.user %></td>
        <td><%= cart.session %></td>
        <td><%= cart.total %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="container" id="checkout-page">
	<h2 style="font-family:'Lato'">Shopping cart</h2>
	<div class="well">
		<div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th width="120px"></th>
            <th>Model</th>
            <th>Quantity</th>
            <th>Price / Case</th>
            <th>Total</th>
            <th width="80px"></th>
          </tr>
        </thead>

        <tbody>
          <% @orders.each do |order| %>
            <tr>
            	<td><%= link_to edit_order_path(order) do %>
            		<div style="height:164px; width: 120px; overflow: hidden;"><iframe style="height:1400px; width:900px; zoom: 0.35; -webkit-transform:scale(0.35); margin-top:-470px; margin-left: -300px;" src="/orders/<%= order.id %>"></iframe></div>
            		<% end %></td>
            	<td><%= order.model %></td>
            	<td><%= order.quantity %></td>
            	<td><%= number_to_currency(order.price, options = {format: "%u%n", precision: 0}) %></td>
            	<td><%= number_to_currency(order.quantity * order.price, options = {format: "%u%n", precision: 0})  %></td>
            	<td>
            		<%= link_to edit_order_path(order) do %>
            			<span class="glyphicon glyphicon-pencil" style="margin-right: 10px;"></span>
            		<% end %>
            		<%= link_to order, method: :delete, data: { confirm: 'Are you sure?' }, :class => "flatred" do %>
            			<span class="glyphicon glyphicon-remove"></span>
            		<% end %>
            	</td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
	</div>

	<h5 style="text-align:right">Shipping (4-6 days): <span style="text-decoration: line-through">$5.00</span> <span class="flatgreen">FREE</span><br></h5>
	<h4 style="text-align:right">Total: <%= number_to_currency(@cart_total, options = {format: "%u%n", precision: 2}) %><br><br>
	<%= form_tag charges_path do %>
	  <script
	    src="https://checkout.stripe.com/checkout.js"
	    class="stripe-button"
	    data-key="pk_test_QcvyHZ0UZEHJqCsbOtuHsGTc"
	    data-image="/images/instacase_small.png"
	    data-name="Order of <%= @cart_items %> Custom Case(s)"
	    data-description='Total <%= number_to_currency(@cart_total, options = {format: "%u%n", precision: 2}) %>'
	    data-amount="<%= @cart_total * 100 %>"
	    data-shipping-address="true">
	  </script>
	<% end %></h4>
	<hr>
	<h4 style="text-align:right; font-family: 'Lato';" class="darkgray">We proudly accept <img style="height:auto; width: 200px;" src="/images/creditcards.jpg"/></h4>
	
	<br>
	<br>
	<br>
	<br>>
</div>

app/views/carts/thankyou.html.erb
	<div class="container-fluid">
		<br><br>
		<center><h2 class="thin-font insta-title">Thank you for your order!</h2>
		

		<h4 class="darkgray">Your order is confirmed and should be arriving within 7-10 days. You'll soon be receiving a confirmation email.</h4>

		<br><br>
		
		<div class="row" id="home-buttons">
			<div class="col-md-12">
				<a href="/choose">
					<div class="btn btn-block large-button btn-primary">
						Create another case <i class="fa fa-flask"></i>
					</div>
				</a>
			</div>
		</div>

		</center>


		<br>
		<br>
		<br>
		<br>
	</div>